config/routes.rb
Rails.application.routes.draw do
  
  resources :episodes, only: %i[new create index]

  root to: 'episodes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  include EpisodeUploader[:track]

  validates :title, presence: true
  validates :date,  presence: true
  validates :track, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  layout 'admin'

  def index
    @episodes = Episode.all
  end

  def new
    @episode = Episode.new
  end

  def create
    @episode = Episode.new episode_params
    if @episode.save
      redirect_to episodes_path
    else
      render :new
    end
  end

  private

  def episode_params
    params.require(:episode).permit(:title, :date, :track)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/_episode.html.erb
<div>
  <p><strong><%= episode.title %></strong> by <%= episode.date %></p>
  <%= link_to 'Listen', episode.track.url(public: true) %>
</div>
<hr>

app/views/episodes/_form.html.erb
<%= form_with model: episode do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div>
    <%= f.label :track %>
    <%= f.file_field :track %>
  </div>

  <%= f.submit %>
<% end %>

app/views/episodes/edit.html.erb
<h1>Edit Episode</h1>


<%= render 'form', episode: @episode %>

app/views/episodes/index.html.erb
<h1>Episodes</h1>

<p><%= link_to 'Add Episode', new_episode_path %></p>

<%= render @episodes %>

app/views/episodes/new.html.erb
<h1>Add episode</h1>

<%= render 'form', episode: @episode %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>NDQ Radio Admin</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ndqradio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>